requests:
  -
    hosts:
      - nbt.com
    filters:
      - root.pem
    filter_type: 0
    response:
      datatype: 1
      data: "./rootCA.pem"
      headers:
        Content-Disposition:
          - attachment
            filename='rootCA.pem'
        Content-type:
          - "PEM certificate"

  -
    hosts:
      - r1.snnd.co
    filter_type: 0
    filters:
      - main.html
    response:
      datatype: 1
      data: /home/ps/MacbookLocal/jstag/main.html
      headers:
        Content-type:
          - text/html
